routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'digging_deeper'], function () {
	Route::get('collections', 'DiggingDeeperController@collections')
	->name('dipping_deeper.collections');

	Route::get('process-video', 'DiggingDeeperController@processVideo')
	->name('dipping_deeper.processVideo');

	Route::get('prepare-catalog', 'DiggingDeeperController@prepareCatalog')
	->name('dipping_deeper.prepareCatalog');
});

Route::group(['namespace' => 'Blog', 'prefix' => 'blog'], function () {
	Route::resource('posts', 'PostController')->names('blog.posts');
});

// Адмінка Блога
$groupData = [
	'namespace'=> 'Blog\Admin',
	'prefix' => 'admin/blog'
];
Route::group($groupData, function () {
	// BlogCategory
	$method = ['index', 'edit', 'update', 'create', 'store'];
	Route::resource('categories', 'CategoryController')
	     ->only($method)
	     ->names('blog.admin.categories');

	// BlogPost
	Route::resource('posts', 'PostController')
	     ->except(['show'])
	     ->names('blog.admin.posts');
	Route::get('posts/{post}/restore', 'PostController@restore')->name('blog.admin.posts.restore');
});

//Route::resource('rest', 'RestTestController')->names('restTest');

app/Models/BlogCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class BlogCategory
 *
 * @package App\Models
 *
 * @property-read BlogCategory $parentCategory
 * @property-read string $parentTitle
 */
class BlogCategory extends Model
{
    use SoftDeletes;

	/**
	 * Id корня
	 */
    const ROOT = 1;

    protected $fillable = [
    	'title',
    	'slug',
    	'parent_id',
    	'description',
    ];

	/**
	 * Отримання батьківської категорії
	 *
	 * @return BelongsTo
	 */
    public function parentCategory(): BelongsTo
	{
		return $this->belongsTo(BlogCategory::class, 'parent_id', 'id');
	}

	/**
	 * Приклад аксесуара (Accessor)
	 *
	 * @url https://laravel.com/docs/5.8/eloquent-mutators
	 *
	 * @return string
	 */
	public function getParentTitleAttribute(): string
	{
		return $this->parentCategory->title
			   ?? ($this->isRoot()
				? 'Корінь'
				: '???');
	}

	/**
	 * Чи являється теперішній обʼєкт корневим
	 *
	 * @return bool
	 */
	public function isRoot(): bool
	{
		return $this->id === BlogCategory::ROOT;
	}

	/**
	 * Приклад аксесуара
	 *
	 * @param string $valueFromObject
	 *
	 * @return string
	 */
	public function getTitleAttribute(string $valueFromObject): string
	{
		return mb_strtoupper($valueFromObject);
	}

	/**
	 * Приклад мутатора
	 *
	 * @param string $valueFromObject
	 */
	public function setTitleAttribute(string $valueFromObject)
	{
		$this->attributes['title'] =  mb_strtolower($valueFromObject);
	}
}

app/Http/Controllers/Blog/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Blog\Admin;

use App\Http\Requests\BlogCategoryCreateRequest;
use App\Http\Requests\BlogCategoryUpdateRequest;
use App\Models\BlogCategory;
use App\Repositories\BlogCategoryRepository;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

/**
 * Управління категоріями блогу в адмінці
 *
 * Class CategoryController
 *
 * @package App\Http\Controllers\Blog\Admin
 */
class CategoryController extends BaseController
{
	/**
	 * @var BlogCategoryRepository
	 */
	private $blogCategoryRepository;

	public function __construct()
	{
		parent::__construct();

		$this->blogCategoryRepository = app(BlogCategoryRepository::class);
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return View
	 */
	public function index(): View
    {
		$paginator = $this->blogCategoryRepository->getAllWithPaginate(25);

		return view('blog.admin.categories.index', compact('paginator'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return View
	 */
	public function create(): View
    {
		$item = BlogCategory::make();
		$categoryList = $this->blogCategoryRepository->getForComboBox();

		return view('blog.admin.categories.edit', compact('item', 'categoryList'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param BlogCategoryCreateRequest $request
	 *
	 * @return RedirectResponse
	 */
	public function store(BlogCategoryCreateRequest $request): RedirectResponse
    {
		$data = $request->input();
		// Створити обʼєкт та додати в БД
		$item = BlogCategory::create($data);

		if ($item->exists) {
			return redirect()->route('blog.admin.categories.edit', [$item->id])
			                 ->with(['success' => 'Успішно збережено']);
		} else {
			return back()->withErrors(['msg' => 'Помилка збереження'])
			             ->withInput();
		}
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param int $id
	 *
	 * @return View
	 */
	public function edit(int $id): View
    {
		$item = $this->blogCategoryRepository->getEdit($id);

		if (empty($item)) {
			abort(404);
		}

		$categoryList = $this->blogCategoryRepository->getForComboBox();

		return view('blog.admin.categories.edit',
			compact('item', 'categoryList'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param BlogCategoryUpdateRequest $request
	 * @param int $id
	 *
	 * @return RedirectResponse
	 */
	public function update(BlogCategoryUpdateRequest $request, int $id): RedirectResponse
    {
		$item = $this->blogCategoryRepository->getEdit($id);

		if (empty($item)) {
			return back()
				->withErrors(['msg' => "Запис id=[{$id}] не знайдений!"])
				->withInput();
		}

		$data = $request->all();
		$result = $item->update($data);

		if ($result) {
			return redirect()
				->route('blog.admin.categories.edit', $item->id)
				->with(['success' => 'Успішно збережено!']);
		} else {
			return back()
				->withErrors(['msg' => 'Помилка збереження!'])
				->withInput();
		}
	}
}

resources/views/blog/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')
    @php /** @var App\Models\BlogCategory $item */ @endphp
    @if($item->exists)
        <form method="POST" action="{{ route('blog.admin.categories.update', $item->id) }}">
        @method('PATCH')
    @else
        <form method="POST" action="{{ route('blog.admin.categories.store') }}">
    @endif
        @csrf
        <div class="container">
            @php /** @var Illuminate\Support\ViewErrorBag $errors */ @endphp
            @if($errors->any())
                <div class="row justify-content-center">
                    <div class="col-md-11">
                        <div class="alert alert-danger" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            {!! $errors->first() !!}
                        </div>
                    </div>
                </div>
            @endif
            @if(session('success'))
                <div class="row justify-content-center">
                    <div class="col-md-11">
                        <div class="alert alert-success" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            {{ session('success') }}
                        </div>
                    </div>
                </div>
            @endif
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('blog.admin.categories.includes.item_edit_main_col')
                </div>
                <div class="col-md-3">
                    @include('blog.admin.categories.includes.item_edit_add_col')
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/blog/admin/categories/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
                    <a class="btn btn-primary" href="{{ route('blog.admin.categories.create') }}">
                        Додати
                    </a>
                </nav>
                <div class="card">
                    <div class="card-body">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Категорія</th>
                                    <th>Батько</th>
                                </tr>
                            </thead>
                            <tbody>
                            @php /** @var Illuminate\Contracts\Pagination\LengthAwarePaginator $paginator */ @endphp
                            @foreach($paginator as $item)
                                @php /** @var App\Models\BlogCategory $item */ @endphp
                                <tr>
                                    <td>{{ $item->id }}</td>
                                    <td>
                                        <a href="{{ route('blog.admin.categories.edit', $item->id) }}">
                                            {{ $item->title }}
                                        </a>
                                    </td>
                                    <td @if(in_array($item->parent_id, [0, 1])) class="text-secondary" @endif>
                                        {{--{{ $item->parent_id }}--}}
                                        {{--{{ $item->parentCategory->title ?? '?' }}--}}
                                        {{--{{ optional($item->parentCategory)->title }}--}}
                                        {{--{{
                                            $item->parentCategory->title
                                                ?? ($item->id === \App\Models\BlogCategory::ROOT
                                                    ? 'Корінь'
                                                    : '???')
                                        }}--}}
                                        {{--{{ $item->parent_title }}--}}
                                        {{ $item->parentTitle }}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        @if($paginator->total() > $paginator->count())
            <br>
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            {{ $paginator->links() }}
                        </div>
                    </div>
                </div>
            </div>
        @endif
    </div>
@endsection