routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'digging_deeper'], function () {
	Route::get('collections', 'DiggingDeeperController@collections')
	->name('dipping_deeper.collections');

	Route::get('process-video', 'DiggingDeeperController@processVideo')
	->name('dipping_deeper.processVideo');

	Route::get('prepare-catalog', 'DiggingDeeperController@prepareCatalog')
	->name('dipping_deeper.prepareCatalog');
});

Route::group(['namespace' => 'Blog', 'prefix' => 'blog'], function () {
	Route::resource('posts', 'PostController')->names('blog.posts');
});

// Адмінка Блога
$groupData = [
	'namespace'=> 'Blog\Admin',
	'prefix' => 'admin/blog'
];
Route::group($groupData, function () {
	// BlogCategory
	$method = ['index', 'edit', 'update', 'create', 'store'];
	Route::resource('categories', 'CategoryController')
	     ->only($method)
	     ->names('blog.admin.categories');

	// BlogPost
	Route::resource('posts', 'PostController')
	     ->except(['show'])
	     ->names('blog.admin.posts');
	Route::get('posts/{post}/restore', 'PostController@restore')->name('blog.admin.posts.restore');
});

//Route::resource('rest', 'RestTestController')->names('restTest');

app/Http/Controllers/Blog/Admin/PostController.php
<?php

namespace App\Http\Controllers\Blog\Admin;

use App\Http\Requests\BlogPostCreateRequest;
use App\Http\Requests\BlogPostUpdateRequest;
use App\Jobs\BlogPostAfterCreateJob;
use App\Jobs\BlogPostAfterDeleteJob;
use App\Models\BlogPost;
use App\Repositories\BlogCategoryRepository;
use App\Repositories\BlogPostRepository;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\View\View;

/**
 * Управління статями блога
 *
 * Class PostController
 *
 * @package App\Http\Controllers\Blog\Admin
 */
class PostController extends BaseController
{
	/**
	 * @var BlogPostRepository
	 */
	private $blogPostRepository;

	/**
	 * @var BlogCategoryRepository
	 */
	private $blogCategoryRepository;

	/**
	 * PostController constructor.
	 */
	public function __construct()
	{
		parent::__construct();

		$this->blogPostRepository = app(BlogPostRepository::class);
		$this->blogCategoryRepository = app(BlogCategoryRepository::class);
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return View
	 */
    public function index(): View
    {
	    $paginator = $this->blogPostRepository->getAllWithPaginate();

        return view('blog.admin.posts.index', compact('paginator'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
	{
        $item = new BlogPost();
        $categoryList = $this->blogCategoryRepository->getForComboBox();

        return view('blog.admin.posts.edit', compact('item', 'categoryList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param BlogPostCreateRequest $request
     *
     * @return RedirectResponse
	 */
    public function store(BlogPostCreateRequest $request): RedirectResponse
	{
		$data = $request->input();
		$item = BlogPost::create($data);

		if ($item) {
			$job = new BlogPostAfterCreateJob($item);
			$this->dispatch($job);

			return redirect()->route('blog.admin.posts.edit', [$item->id])
							 ->with(['success' => 'Успішно збережено']);
		} else {
			return back()->withErrors(['msg' => 'Помилка збереження'])
						 ->withInput();
		}
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return View
     */
    public function edit(int $id): View
    {
        $item = $this->blogPostRepository->getEdit($id);

        if (empty($item)) {
            abort(404);
        }

        $categoryList = $this->blogCategoryRepository->getForComboBox();

        return view('blog.admin.posts.edit',
            compact('item', 'categoryList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param BlogPostUpdateRequest $request
     * @param int $id
     *
     * @return RedirectResponse
     */
    public function update(BlogPostUpdateRequest $request, int $id): RedirectResponse
    {
        $item = $this->blogPostRepository->getEdit($id);

        if (empty($item)) {
            return back()
                ->withErrors(['msg' => "Запис id=[{$id}] не знайдений"])
                ->withInput();
        }

        $data = $request->all();
        $request = $item->update($data);

        if ($request) {
            return redirect()
                ->route('blog.admin.posts.edit', $item->id)
                ->with(['success' => 'Збережено вдало']);
        } else {
            return back()
                ->withErrors(['msg' => 'Помилка збереження'])
                ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
	 * @return RedirectResponse
	 */
    public function destroy(int $id): RedirectResponse
	{
    	// Софт видалення, в БД залишиться
	    $result = BlogPost::destroy($id);

	    // Повне видалення
		//$result = BlogPost::find($id)->forceDelete();

	    if ($result) {
	    	BlogPostAfterDeleteJob::dispatch($id)->delay(20);

	    	//> Варіанти запуска:
	    	//BlogPostAfterDeleteJob::dispatchNow();

			//dispatch(new BlogPostAfterDeleteJob($id));
			//dispatch_now(new BlogPostAfterDeleteJob($id));

			//$this->dispatch(new BlogPostAfterDeleteJob($id));
			//$this->dispatchNow(new BlogPostAfterDeleteJob($id));

			/*$job = new BlogPostAfterDeleteJob($id);
			$job->handle();*/
			//< Варіанти запуска.

			$restoreLink = '<a href="'. route('blog.admin.posts.restore', $id) . '">посилання</a>';

	    	return redirect()
				->route('blog.admin.posts.index')
				->with(['success' => "Запис id[$id] видалений.\n<br>" .
									 "Для відновлення запису id[$id] натисніть на $restoreLink."]);
		} else {
	    	return back()->withErrors(['msg' => 'Помилка видалення']);
		}
	}

	/**
	 * Restore the specified resource from storage.
	 *
	 * @param int $id
	 *
	 * @return RedirectResponse
	 */
	public function restore(int $id): RedirectResponse
	{
		$blogPost = BlogPost::onlyTrashed()->find($id);

		if ($blogPost) {
			$blogPost->restore();
			return redirect()
				->route('blog.admin.posts.edit', $id)
				->with(['success' => "Запис id[$id] відновлений"]);
		} else {
			return back()->withErrors(['msg' => "Неможливо відновити запис id[$id]"]);
		}
    }
}

app/Http/Controllers/Blog/PostController.php
<?php

namespace App\Http\Controllers\Blog;

use App\Models\BlogPost;
use Illuminate\Http\Request;
use Illuminate\View\View;

class PostController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index()
    {
    	$items = BlogPost::all();

    	return view('blog.posts.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/blog/admin/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @php /** @var App\Models\BlogPost $item */ @endphp
        @if($item->exists)
            <form method="POST" action="{{ route('blog.admin.posts.update', $item->id) }}">
            @method('PATCH')
        @else
            <form method="POST" action="{{ route('blog.admin.posts.store') }}">
        @endif
            @csrf
            @include('blog.admin.posts.includes.result_messages')
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include('blog.admin.posts.includes.post_edit_main_col')
                </div>
                <div class="col-md-3">
                    @include('blog.admin.posts.includes.post_edit_add_col')
                </div>
            </div>
        </form>
        @if($item->exists)
            <br>
            <form method="POST" action="{{ route('blog.admin.posts.destroy', $item->id) }}">
                @method('DELETE')
                @csrf
                <div class="row justify-content-center">
                    <div class="col-md-8">
                        <div class="card card-block">
                            <div class="card-body ml-auto">
                                <button type="submit" class="btn btn-link">Видалити</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3"></div>
                </div>
            </form>
        @endif
    </div>
@endsection

resources/views/blog/admin/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">

                @include('blog.admin.posts.includes.result_messages')

                <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
                    <a class="btn btn-primary" href="{{ route('blog.admin.posts.create') }}">
                        Написати
                    </a>
                </nav>
                <div class="card">
                    <div class="card-body">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Автор</th>
                                <th>Категорія</th>
                                <th>Заголовок</th>
                                <th>Дата публікації</th>
                            </tr>
                            </thead>
                            <tbody>
                            @php /** @var Illuminate\Contracts\Pagination\LengthAwarePaginator $paginator */ @endphp
                            @foreach($paginator as $post)
                                @php /** @var App\Models\BlogPost $post */ @endphp
                                <tr @if(!$post->is_published) style="background-color: #ccc;" @endif>
                                    <td>{{ $post->id }}</td>
                                    <td>{{ $post->user->name }}</td>
                                    <td>{{ $post->category->title }}</td>
                                    <td>
                                        <a href="{{ route('blog.admin.posts.edit', $post->id) }}">
                                            {{ $post->title }}
                                        </a>
                                    </td>
                                    <td>
                                        {{ $post->published_at ? \Carbon\Carbon::parse($post->published_at)->format('d.M H:i') : '' }}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        @if($paginator->total() > $paginator->count())
            <br>
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            {{ $paginator->links() }}
                        </div>
                    </div>
                </div>
            </div>
        @endif
    </div>
@endsection